create table if not exists public.users (id bigint generated by default as identity primary key,username text not null unique,pin_hash text not null,progress jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
create table if not exists public.sessions (token_hash text primary key,user_id bigint not null references public.users(id) on delete cascade,expires_at timestamptz not null,created_at timestamptz not null default now());
create index if not exists sessions_user_id_idx on public.sessions(user_id);
create index if not exists sessions_expires_at_idx on public.sessions(expires_at);
alter table public.users enable row level security;
alter table public.sessions enable row level security;
